### PR TITLE
Add basic decision making

### PR DESCRIPTION
**Pull request by Razvan00Rusu**

### CODE REVIEW

**Comment by Razvan00Rusu** [comment]
A change somewhere has made this fork a lot slower than the main repo. I don't think it is this PR specifically necessarily because even main on this fork is a lot slower - at least on my machine :/

**Comment by Razvan00Rusu** [comment]
> A change somewhere has made this fork a lot slower than the main repo. I don't think it is this PR specifically necessarily because even main on this fork is a lot slower - at least on my machine :/

Nvm Nvm I missed a sleep that was merged in through main all good.

**Comment by thl19git** [comment]
I have merged upstream/main, which breaks a lot of things with the update Agent interface.

**Comment by Razvan00Rusu** [comment]
Old Old Old

**Pull request closed without merging**
